#Configure the host server:
server:
  port: 8080
  servlet:
    context-path: /taxes

#Configure MongoDB:
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: rootuser
      password: rootpass
      database: taxes
      authentication-database: admin
      auto-index-creation: true